version: '3.8'

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_express
    restart: always
    env_file:
      - .env
    ports:
      - 1433:1433
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data: